name: Build and release PDF

on: push

jobs:
  pdf:
    runs-on: ubuntu-22.04

    container:
      image: texlive/texlive

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: |
          sh .github/scripts/build_pdf.sh built_pdfs

      # Upload artifact for each CI run. Not needed for release_if_tag! This
      # uses the output of steps.build .
      - name: upload artifact
        uses: actions/upload-artifact@master
        with:
          name: built_pdfs
          path: built_pdfs

      # Create a release and attach built_pdfs/*.pdf to that for easy download.
      - name: release_if_tag
        uses: softprops/action-gh-release@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "built_pdfs/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
